version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: booking_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking-net

  redis:
    image: redis:7
    container_name: booking_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - booking-net

volumes:
  postgres_data:

networks:
  booking-net:
    driver: bridge