spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  application:
    name: booking-system

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080